ark:
  api_key: ""
  base_url: "https://ark.cn-beijing.volces.com/api/v3"
  enrich_model: "deepseek-v3-1-terminus"
  enrich_template_path: "./prompts/enrich_questions.txt"
  embedding_model: "doubao-embedding-large-text-240915" # 已废弃，改用 Gemini

gemini:
  api_key: ""
  embedding_model: "gemini-embedding-001"

database:
  dsn: ""
